apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cc.ccloud-secrets
  namespace: default
spec:
  encryptedData:
    CCLOUD_EMAIL: AgBNUpMZnvdjVDF0vV7RbV3eMZ3fCQAt45vIr4qU2gGrndyq7TDKjCrjgwbtxQITtzNmMfNwfSnpNv2BHv5V09irj+PNDWlF0X1nqzK6F0VLwJHdrgnCTdbrZ9+oERPNzGWN4WXZCJfyrZKVMu1UJ35piQBtCB9PpC60PYN+KQJjtH6O0XLjZCOnbfgj1geUK7Yy6kgCOcqw5h8c25Iwfv2v/Og2VWxbN+ma3Lzf1W2QzLwiF32+6g0IbqQg+A0sKJKiZAy38yYx7ICyuOCy56EByF3nmPXRVxwajgVXOo2TfzwREYSgnG7So9dFkBo+IJuuVpEt0Eqg/Pm2r8GlFxqR/IT2y0TuXqusE7RHlsDArPrlFpmRvk60bM97Fn0gwxJYh228+1w/4yxfwa1eSE63KzJDW+uHpvhMHMXc9ewu7DTDKn+9J5VApm+hrPd9vJ+UtHRjFNCrBmXi2ZEJ9v3I1gw4/27HCZzxp5U9KKvKluTqP9pElILW/asG8MMxcZnz0kVxf4a0BvL9GvnmQNZ/roJ+pJuFHNc58+okcV+dAp6EoU1nwSfFv4KVSL82mWV+bCy+jlIDmQr0pUDBk72CScjLtKTGL7SzpfgsLqYw5sVXtUVaJZThYoquCD6n0ML+qXMpp0+UNqHxvGYfGbXnCd4cAmT8jxV2ZJru9MMN8pACNc4xNxU9kM7cdPW0X5IQteC5xyF7CRPb8xv5SFuG0w==
    CCLOUD_PASSWORD: AgAhSJsa1wVmUcgsqyKn2KCiiTgi6g2tgNePWZeqLLvhxCPbhpnOxUWgvfrBGkjukyLFgUx//W9oyVnXs8nQE3naBFNu78iAiXDlJvsUkzCeTtYydg5JtudtXaaMCd18layXMIKlLpXB0XNzd8qTohhfbTKY2BYUxklChSqj7Yw+7EdnHyiHdFfY8kfJWVMoh7uFIztJcry13l+Q8sSdMtnjryukqtgDK55shm/dDeenoBDua7GKe0USWv0AkXOWSkZhoaA3ZyLPJyvBwZ7YtyCi1Z4wTy5oEm+C1gu6KKHa0jhyzfhfPVMmnc2JzVxh2JHFLUcy/WCghrp9V6TpuV7a3MWj/zMUqEO0pDyvqJDKow36N8MRxiW6g+OvLpBJJqrbzXu+ePAnhEJgwUostIxzWM/4VxhNK58e2xYhLc6weJgHsx6EgXqmvxTMRpqHjNImnyig39/tDMzNtD+s+suf5rcfKzv+Nvas00GBA7xNu42cMT8dDklSRXpq55apVpb7fhx+/4EG+dJUGDecb9j+W/4BLXiSdqcv7DwpG4g9ibZ89bZDSdsFWM3nKz08ecd4y5m/Nf560wZdrq22kMSH5uwH9gw4CEdsS08yiVMXUqdIdJTWkY6uGRkeUXpeq8xwOrE8QM4G3so0dI2V/Gxz1IhyrlS+pGFSqwLbdMHbqCUWTmRnc5KPA3FM35I6Rci+t8wO494yryqPTKRRL/cJR0I=
  template:
    metadata:
      creationTimestamp: null
      name: cc.ccloud-secrets
      namespace: default

